### PR TITLE
Added Builder and ToBuilder instances for Data.ByteString.Builder

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Hi Michael,

I'm not sure if you're still maintaining this library, but I recently discovered it while trying out ClassyPrelude for the first time. I added Builder and ToBuilder instances for Data.ByteString.Builder, but I had to drop a the "lazy -> builder" fundep on Builder because both types build lazy ByteStrings.

### CODE REVIEW

**Comment by snoyberg** [comment]
Yes, I'm still maintaining this library; I use it mostly via classy-prelude. The problem with this change is that it would break type inference. One approach to get instances for bytestring-builder would be to add a newtype around lazy ByteStrings for the type checking.

Additionally, any usage of bytestring builder needs to be conditionalized on the version of bytestring being used.

**Comment by mitchellwrosen** [comment]
Ah. Would you like to see these changes made, or should I just close the issue? I reworked my (client) code a little bit and it turns out I don't need the instances anymore :)

**Comment by snoyberg** [comment]
I personally have no need for bytestring-builder instances yet, but I'm guessing someone out there would be able to take advantage of them. Your call.

**Comment by snoyberg** [comment]
This is no longer necessary, since bytestring-builder and blaze-builder share the same types from the bytestring package.

**Pull request closed without merging**
